version: '2'
services:
  solar-equipment-management:
    image: solar-equipment-management:latest
    ports:
      - "11429:1429"
    container_name: solar-equipment-management
    restart: always
    volumes:
      - /usr/local/docker-compose-test/solar-equipment-management/application-dev.yml:/home/application-dev.yml
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 10.6.5.192:24224
        tag: solar-equipment-management-devtest
  solar-log-receiver:
    image: solar-log-receiver:latest
    ports:
      - "18088:8088"
    container_name: solar-log-receiver
    restart: always
    volumes:
      - /usr/local/docker-compose-test/solar-log-receiver/application-dev.yml:/home/application-dev.yml
      - /usr/local/docker-compose-test/wait-for-it.sh:/home/wait-for-it.sh
    links:
      - solar-equipment-management
    depends_on:
      - solar-equipment-management
    entrypoint: "/home/wait-for-it.sh -t 0 solar-equipment-management:2429 -- "
    command: ["java", "-jar", "app.jar"]
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 10.6.5.192:24224
        tag: solar-log-receiver-devtest
  solar-log-parser:
    image: solar-log-parser:latest
    ports:
      - "18083:8083"
    container_name: solar-log-parser
    restart: always
    volumes:
      - /usr/local/docker-compose-test/solar-log-parser/application-dev.yml:/home/application-dev.yml
      - /usr/local/docker-compose-test/wait-for-it.sh:/home/wait-for-it.sh
    links:
      - solar-equipment-management
    entrypoint: "/home/wait-for-it.sh -t 0 solar-equipment-management:2429 -- "
    command: ["java", "-jar", "app.jar"]
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 10.6.5.192:24224
        tag: solar-log-parser-devtest
  solar-log-inquirer:
    image: solar-log-inquirer:latest
    ports:
      - "18084:8084"
    container_name: solar-log-inquirer
    volumes:
      - /usr/local/docker-compose-test/solar-log-inquirer/application-dev.yml:/home/application-dev.yml
      - /usr/local/docker-compose-test/wait-for-it.sh:/home/wait-for-it.sh
    links:
      - solar-equipment-management
    depends_on:
      - solar-equipment-management
    entrypoint: "/home/wait-for-it.sh -t 0 solar-equipment-management:2429 -- "
    command: ["java", "-jar", "app.jar"]
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 10.6.5.192:24224
        tag: solar-log-inquirer-devtest
  solar-equipment-monitor:
    image: solar-equipment-monitor:latest
    ports:
      - "18082:8082"
    container_name: solar-equipment-monitor
    volumes:
      - /usr/local/docker-compose-test/solar-equipment-monitor/application-dev.yml:/home/application-dev.yml
      - /usr/local/docker-compose-test/wait-for-it.sh:/home/wait-for-it.sh
    links:
      - solar-equipment-management
    depends_on:
      - solar-equipment-management
    entrypoint: "/home/wait-for-it.sh -t 0 solar-equipment-management:2429 -- "
    command: ["java", "-jar", "app.jar"]
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 10.6.5.192:24224
        tag: solar-equipment-monitor-devtest
  solar-equipment-alert:
    image: solar-equipment-alert:latest
    ports:
      - "11428:1428"
    container_name: solar-equipment-alert
    restart: always
    volumes:
      - /usr/local/docker-compose-test/solar-equipment-alert/application-dev.yml:/home/application-dev.yml
      - /usr/local/docker-compose-test/wait-for-it.sh:/home/wait-for-it.sh
    links:
      - solar-equipment-management
    depends_on:
      - solar-equipment-management
    entrypoint: "/home/wait-for-it.sh -t 0 solar-equipment-management:2429 -- "
    command: ["java", "-jar", "app.jar"]
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 10.6.5.192:24224
        tag: solar-equipment-alert-devtest